class AdminBankingOverview {
    constructor(root=document){this.root=root;this.timer=null;this.delay=400;this.onInput=this.onInput.bind(this);this.onChange=this.onChange.bind(this);this.onClick=this.onClick.bind(this);root.addEventListener('input',this.onInput);root.addEventListener('change',this.onChange);root.addEventListener('click',this.onClick);}
    onInput(event){const field=this.closest(event.target,'[data-admin-banking-filters] input[name="q"]');if(!field){return;}window.clearTimeout(this.timer);this.timer=window.setTimeout(()=>this.submit(field.closest('form'),true),this.delay);}
    onChange(event){const field=this.closest(event.target,'[data-admin-banking-filters] select');if(field){this.submit(field.closest('form'),true);}}
    onClick(event){const page=this.closest(event.target,'[data-admin-banking-page]');if(page){event.preventDefault();if(!page.disabled){const form=page.closest('form');this.set(form,'page',page.dataset.adminBankingPage);this.submit(form,false);}return;}const sort=this.closest(event.target,'[data-admin-banking-filters] [data-fg-table-sort]');if(sort){event.preventDefault();const form=sort.closest('form');const next=sort.dataset.fgTableSort||'';const current=form.elements.namedItem('sort').value;const direction=form.elements.namedItem('direction').value;this.set(form,'sort',next);this.set(form,'direction',current===next&&direction==='asc'?'desc':'asc');this.submit(form,true);return;}const reset=this.closest(event.target,'[data-admin-banking-reset]');if(reset){event.preventDefault();const form=reset.closest('form');this.set(form,'q','');this.set(form,'account','');this.set(form,'status','');this.set(form,'flow','all');this.set(form,'year','');this.set(form,'sort','booked_on');this.set(form,'direction','desc');this.submit(form,true);}}
    submit(form,resetPage){if(!form||!form.isConnected){return;}window.clearTimeout(this.timer);if(resetPage){this.set(form,'page','1');}if(typeof form.requestSubmit==='function'){form.requestSubmit();return;}form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));}
    set(form,name,value){const field=form?form.elements.namedItem(name):null;if(field){field.value=String(value);}}
    closest(target,selector){return target instanceof Element?target.closest(selector):null;}
}
if(!window.adminBankingOverview){window.adminBankingOverview=new AdminBankingOverview();}
