<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminBanking\Application\UseCase;
use Flexgrid\Modules\AdminBanking\Contract\BankMatchProcessorInterface;use Flexgrid\Modules\AdminBanking\Contract\BankMatchProposalRepositoryInterface;use Flexgrid\Modules\AdminBanking\Contract\BankTransactionRepositoryInterface;use Flexgrid\Modules\AdminBanking\Domain\Model\BankTransaction;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\BankTransactionStatus;use Flexgrid\Modules\AdminCore\Context\TenantContext;use Flexgrid\Modules\AdminCore\Contract\TransactionManagerInterface;use Flexgrid\Utils\_Time;
final class AcceptBankMatch
{
    private$tenant,$transactionManager,$transactions,$proposals,$processors,$clock;
    public function __construct(TenantContext$tenant,TransactionManagerInterface$transactionManager,BankTransactionRepositoryInterface$transactions,BankMatchProposalRepositoryInterface$proposals,array$processors,_Time$clock){foreach($processors as$processor){if(!$processor instanceof BankMatchProcessorInterface){throw new \InvalidArgumentException('Ongeldige bankmatchprocessor.');}}$this->tenant=$tenant;$this->transactionManager=$transactionManager;$this->transactions=$transactions;$this->proposals=$proposals;$this->processors=$processors;$this->clock=$clock;}
    public function execute(string$transactionPublicId,string$proposalPublicId):BankTransaction{$transactionPublicId=trim($transactionPublicId);$proposalPublicId=trim($proposalPublicId);if($transactionPublicId===''||$proposalPublicId===''){throw new \InvalidArgumentException('Banktransactie en voorstel zijn verplicht.');}$tenant=$this->tenant->getTenantId();return$this->transactionManager->transactional(function()use($tenant,$transactionPublicId,$proposalPublicId):BankTransaction{$transaction=$this->transactions->findByPublicIdForUpdate($tenant,$transactionPublicId);if($transaction===null){throw new \DomainException('Banktransactie is niet gevonden.');}$proposal=null;foreach($this->proposals->findByTransaction($tenant,$transactionPublicId)as$candidate){if($candidate->getPublicId()===$proposalPublicId){$proposal=$candidate;break;}}if($proposal===null){throw new \DomainException('Matchvoorstel is niet gevonden of niet meer geldig.');}if($transaction->getStatus()->getValue()===BankTransactionStatus::MATCHED){if($transaction->getMatchedTargetType()===$proposal->getTargetType()&&$transaction->getMatchedTargetPublicId()===$proposal->getTargetPublicId()){return$transaction;}throw new \DomainException('Banktransactie is al aan een ander doel afgeletterd.');}if($transaction->getStatus()->getValue()!==BankTransactionStatus::UNMATCHED){throw new \DomainException('Deze banktransactie is niet meer open.');}$processor=$this->processor($proposal->getTargetType());$processor->process($tenant,$transaction,$proposal->getTargetPublicId());$timestamp=(int)$this->clock->get();$transaction->match($proposal->getTargetType(),$proposal->getTargetPublicId(),$timestamp);$this->transactions->updateMatchState($transaction,$timestamp);return$transaction;});}
    private function processor(string$targetType):BankMatchProcessorInterface{$matches=[];foreach($this->processors as$processor){if($processor->supports($targetType)){$matches[]=$processor;}}if(count($matches)!==1){throw new \LogicException(count($matches)===0?'Geen verwerker beschikbaar voor dit afletterdoel.':'Meerdere verwerkers claimen hetzelfde afletterdoel.');}return$matches[0];}
}
