<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminBanking\Application\UseCase;
use Flexgrid\Modules\AdminBanking\Application\ReadModel\BankMatchContext;use Flexgrid\Modules\AdminBanking\Application\ReadModel\BankMatchSuggestion;use Flexgrid\Modules\AdminBanking\Contract\BankMatchCandidateProviderInterface;use Flexgrid\Modules\AdminBanking\Contract\BankMatchProposalRepositoryInterface;use Flexgrid\Modules\AdminBanking\Contract\BankTransactionRepositoryInterface;use Flexgrid\Modules\AdminBanking\Domain\Model\BankMatchProposal;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\BankTransactionStatus;use Flexgrid\Modules\AdminCore\Context\TenantContext;use Flexgrid\Modules\AdminCore\Contract\PublicIdGeneratorInterface;use Flexgrid\Modules\AdminCore\Contract\TransactionManagerInterface;use Flexgrid\Utils\_Time;
final class GenerateBankMatchProposals
{
    private$tenant,$ids,$transactionManager,$transactions,$proposals,$providers,$clock;
    public function __construct(TenantContext$tenant,PublicIdGeneratorInterface$ids,TransactionManagerInterface$transactionManager,BankTransactionRepositoryInterface$transactions,BankMatchProposalRepositoryInterface$proposals,array$providers,_Time$clock){foreach($providers as$provider){if(!$provider instanceof BankMatchCandidateProviderInterface){throw new \InvalidArgumentException('Ongeldige bankmatchprovider.');}}$this->tenant=$tenant;$this->ids=$ids;$this->transactionManager=$transactionManager;$this->transactions=$transactions;$this->proposals=$proposals;$this->providers=$providers;$this->clock=$clock;}
    public function execute(string$publicId):array{$tenant=$this->tenant->getTenantId();$transaction=$this->transactions->findByPublicId($tenant,trim($publicId));if($transaction===null){throw new \DomainException('Banktransactie is niet gevonden.');}if($transaction->getStatus()->getValue()!==BankTransactionStatus::UNMATCHED){throw new \DomainException('Alleen een open banktransactie kan nieuwe voorstellen krijgen.');}$context=new BankMatchContext($transaction->getPublicId(),$transaction->getAmount()->getMinorUnits(),$transaction->getAmount()->getCurrency()->getCode(),$transaction->getBookedOn()->getValue(),$transaction->getCounterparty()->getName(),$transaction->getCounterparty()->getIban(),$transaction->getDescription(),$transaction->getReference());$suggestions=[];foreach($this->providers as$provider){foreach($provider->suggest($tenant,$context)as$suggestion){if(!$suggestion instanceof BankMatchSuggestion){throw new \UnexpectedValueException('Matchprovider leverde een ongeldig voorstel.');}$key=$suggestion->getTargetType().'|'.$suggestion->getTargetPublicId();if(!isset($suggestions[$key])||$suggestions[$key]->getConfidenceBasisPoints()<$suggestion->getConfidenceBasisPoints()){$suggestions[$key]=$suggestion;}}}usort($suggestions,function(BankMatchSuggestion$a,BankMatchSuggestion$b):int{return$b->getConfidenceBasisPoints()<=>$a->getConfidenceBasisPoints();});$suggestions=array_slice($suggestions,0,10);$created=(int)$this->clock->get();$models=[];foreach($suggestions as$suggestion){$models[]=new BankMatchProposal($this->ids->generate(),$tenant,$transaction->getPublicId(),$suggestion->getTargetType(),$suggestion->getTargetPublicId(),$suggestion->getConfidenceBasisPoints(),$suggestion->getReason(),$created);}$this->transactionManager->transactional(function()use($tenant,$transaction,$models):void{$this->proposals->replaceForTransaction($tenant,$transaction->getPublicId(),$models);});return['transaction'=>$transaction,'proposals'=>$models];}
}
