<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminBanking\Application\UseCase;
use Flexgrid\Modules\AdminBanking\Application\Command\ImportBankStatementCommand;use Flexgrid\Modules\AdminBanking\Application\ReadModel\BankImportResult;use Flexgrid\Modules\AdminBanking\Contract\BankAccountRepositoryInterface;use Flexgrid\Modules\AdminBanking\Contract\BankImportRepositoryInterface;use Flexgrid\Modules\AdminBanking\Contract\BankStatementParserInterface;use Flexgrid\Modules\AdminBanking\Contract\BankTransactionRepositoryInterface;use Flexgrid\Modules\AdminBanking\Domain\Model\BankImport;use Flexgrid\Modules\AdminBanking\Domain\Model\BankTransaction;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\BankDate;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\BankSourceSnapshot;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\CounterpartySnapshot;use Flexgrid\Modules\AdminBanking\Exception\DuplicateBankImportException;use Flexgrid\Modules\AdminBanking\Exception\DuplicateBankTransactionException;use Flexgrid\Modules\AdminCore\Context\TenantContext;use Flexgrid\Modules\AdminCore\Contract\PublicIdGeneratorInterface;use Flexgrid\Modules\AdminCore\Contract\TransactionManagerInterface;use Flexgrid\Modules\AdminCore\ValueObject\Currency;use Flexgrid\Modules\AdminCore\ValueObject\Money;use Flexgrid\Utils\_Time;
final class ImportBankStatement
{
    private$tenant,$ids,$transactions,$accounts,$imports,$bankTransactions,$parser,$clock;
    public function __construct(TenantContext$tenant,PublicIdGeneratorInterface$ids,TransactionManagerInterface$transactions,BankAccountRepositoryInterface$accounts,BankImportRepositoryInterface$imports,BankTransactionRepositoryInterface$bankTransactions,BankStatementParserInterface$parser,_Time$clock){$this->tenant=$tenant;$this->ids=$ids;$this->transactions=$transactions;$this->accounts=$accounts;$this->imports=$imports;$this->bankTransactions=$bankTransactions;$this->parser=$parser;$this->clock=$clock;}
    public function execute(ImportBankStatementCommand$command):BankImportResult
    {
        $content=str_replace(["\r\n","\r"],"\n",trim($command->getContent()));if($content===''||strlen($content)>10*1024*1024){throw new \InvalidArgumentException('Bankbestand moet tussen 1 byte en 10 MB zijn.');}if(!$this->parser->supports($command->getFormat())){throw new \InvalidArgumentException('Bankimportformaat wordt niet ondersteund.');}$checksum=hash('sha256',$content);$tenant=$this->tenant->getTenantId();
        try{return$this->transactions->transactional(function()use($command,$content,$checksum,$tenant):BankImportResult{$account=$this->accounts->findByPublicId($tenant,$command->getBankAccountPublicId());if($account===null||!$account->isActive()){throw new \DomainException('Actieve bankrekening is niet gevonden.');}$existingImport=$this->imports->findByChecksum($tenant,$account->getPublicId(),$command->getFormat(),$checksum);if($existingImport!==null){return new BankImportResult($existingImport,true);}$parsed=$this->parser->parse($content);$importId=$this->ids->generate();$new=[];$skipped=0;
            foreach($parsed as$row){if($this->normalizeReference($row->getAccountReference())!==$account->getAccountReference()){throw new \DomainException('Bankbestand bevat een regel voor een andere rekening.');}$currency=new Currency($row->getCurrency());if(!$currency->equals($account->getCurrency())){throw new \DomainException('Bankregel gebruikt een andere valuta dan de bankrekening.');}if($this->bankTransactions->findByExternalId($tenant,$account->getPublicId(),$row->getExternalId())!==null){++$skipped;continue;}$new[]=new BankTransaction($this->ids->generate(),$tenant,$account->getPublicId(),$importId,$row->getExternalId(),new BankDate($row->getBookedOn()),Money::fromDecimal($row->getAmount(),$currency),new CounterpartySnapshot($row->getCounterpartyName(),$row->getCounterpartyIban(),$row->getCounterpartyBic()),$row->getDescription(),$row->getReference(),new BankSourceSnapshot($command->getFormat(),$row->getRawHash(),$row->getSourceData()));}
            $timestamp=(int)$this->clock->get();$imported=0;foreach($new as$transaction){try{$this->bankTransactions->insert($transaction,$timestamp);++$imported;}catch(DuplicateBankTransactionException$exception){$existing=$this->bankTransactions->findByExternalId($tenant,$account->getPublicId(),$transaction->getExternalId());if($existing===null){throw$exception;}++$skipped;}}$import=new BankImport($importId,$tenant,$account->getPublicId(),$command->getFormat(),$command->getFileName(),$checksum,count($parsed),$imported,$skipped,$timestamp);$this->imports->insert($import);return new BankImportResult($import,false);
        });}catch(DuplicateBankImportException$exception){$existing=$this->imports->findByChecksum($tenant,$command->getBankAccountPublicId(),$command->getFormat(),$checksum);if($existing!==null){return new BankImportResult($existing,true);}throw$exception;}
    }
    private function normalizeReference(string$value):string{return strtoupper(preg_replace('/\s+/','',trim($value)));}
}
