<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminBanking\Infrastructure\Persistence;
use Flexgrid\Modules\AdminBanking\Contract\BankTransactionRepositoryInterface;use Flexgrid\Modules\AdminBanking\Domain\Model\BankTransaction;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\BankDate;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\BankSourceSnapshot;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\BankTransactionStatus;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\CounterpartySnapshot;use Flexgrid\Modules\AdminBanking\Exception\DuplicateBankTransactionException;use Flexgrid\Modules\AdminCore\ValueObject\Currency;use Flexgrid\Modules\AdminCore\ValueObject\Money;use Flexgrid\Modules\AdminCore\ValueObject\TenantId;
final class PdoBankTransactionRepository implements BankTransactionRepositoryInterface
{
    private$connection;public function __construct(\PDO$connection){$this->connection=$connection;}
    public function insert(BankTransaction$transaction,int$createdAt):void{$this->assertTransaction();$statement=$this->connection->prepare('INSERT INTO `admin_bank_transaction` (`tenant_id`,`public_id`,`bank_account_public_id`,`bank_import_public_id`,`external_id`,`booked_on`,`amount_minor`,`currency`,`counterparty_snapshot`,`description`,`reference`,`source_snapshot`,`status`,`matched_target_type`,`matched_target_public_id`,`matched_at`,`created_at`,`updated_at`) VALUES (:tenant,:public,:account,:import,:external,:booked,:amount,:currency,:counterparty,:description,:reference,:source,:status,:target_type,:target_public,:matched_at,:created,:updated)');try{$statement->execute([':tenant'=>$transaction->getTenantId()->toString(),':public'=>$transaction->getPublicId(),':account'=>$transaction->getBankAccountPublicId(),':import'=>$transaction->getBankImportPublicId(),':external'=>$transaction->getExternalId(),':booked'=>$transaction->getBookedOn()->getValue(),':amount'=>$transaction->getAmount()->getMinorUnits(),':currency'=>$transaction->getAmount()->getCurrency()->getCode(),':counterparty'=>$this->json($transaction->getCounterparty()->toArray()),':description'=>$transaction->getDescription(),':reference'=>$transaction->getReference()===''?null:$transaction->getReference(),':source'=>$this->json($transaction->getSourceSnapshot()->toArray()),':status'=>$transaction->getStatus()->getValue(),':target_type'=>$transaction->getMatchedTargetType()===''?null:$transaction->getMatchedTargetType(),':target_public'=>$transaction->getMatchedTargetPublicId()===''?null:$transaction->getMatchedTargetPublicId(),':matched_at'=>$transaction->getMatchedAt(),':created'=>$createdAt,':updated'=>$createdAt]);}catch(\PDOException$exception){if((string)$exception->getCode()==='23000'){throw new DuplicateBankTransactionException('Bankregel is al geïmporteerd.',0,$exception);}throw$exception;}}
    public function findByExternalId(TenantId$tenant,string$account,string$externalId):?BankTransaction{return$this->find('`tenant_id`=:tenant AND `bank_account_public_id`=:account AND `external_id`=:external',[':tenant'=>$tenant->toString(),':account'=>trim($account),':external'=>trim($externalId)]);}
    public function findByPublicId(TenantId$tenant,string$publicId):?BankTransaction{return$this->find('`tenant_id`=:tenant AND `public_id`=:public',[':tenant'=>$tenant->toString(),':public'=>trim($publicId)]);}
    public function findByPublicIdForUpdate(TenantId$tenant,string$publicId):?BankTransaction{$this->assertTransaction();return$this->find('`tenant_id`=:tenant AND `public_id`=:public',[':tenant'=>$tenant->toString(),':public'=>trim($publicId)],true);}
    public function updateMatchState(BankTransaction$transaction,int$updatedAt):void{$this->assertTransaction();$statement=$this->connection->prepare('UPDATE `admin_bank_transaction` SET `status`=:status,`matched_target_type`=:type,`matched_target_public_id`=:target,`matched_at`=:matched,`updated_at`=:updated WHERE `tenant_id`=:tenant AND `public_id`=:public');$statement->execute([':status'=>$transaction->getStatus()->getValue(),':type'=>$transaction->getMatchedTargetType()===''?null:$transaction->getMatchedTargetType(),':target'=>$transaction->getMatchedTargetPublicId()===''?null:$transaction->getMatchedTargetPublicId(),':matched'=>$transaction->getMatchedAt(),':updated'=>$updatedAt,':tenant'=>$transaction->getTenantId()->toString(),':public'=>$transaction->getPublicId()]);if($statement->rowCount()<1&&$this->findByPublicId($transaction->getTenantId(),$transaction->getPublicId())===null){throw new \RuntimeException('Banktransactie bestaat niet meer.');}}
    private function find(string$where,array$parameters,bool$forUpdate=false):?BankTransaction{$statement=$this->connection->prepare('SELECT * FROM `admin_bank_transaction` WHERE '.$where.' LIMIT 1'.($forUpdate?' FOR UPDATE':''));$statement->execute($parameters);$row=$statement->fetch(\PDO::FETCH_ASSOC);return is_array($row)?$this->hydrate($row):null;}
    private function hydrate(array$row):BankTransaction{$currency=new Currency((string)$row['currency']);return new BankTransaction((string)$row['public_id'],new TenantId((string)$row['tenant_id']),(string)$row['bank_account_public_id'],(string)$row['bank_import_public_id'],(string)$row['external_id'],new BankDate((string)$row['booked_on']),new Money((int)$row['amount_minor'],$currency),CounterpartySnapshot::fromArray($this->decode((string)$row['counterparty_snapshot'])),(string)$row['description'],(string)($row['reference']??''),BankSourceSnapshot::fromArray($this->decode((string)$row['source_snapshot'])),new BankTransactionStatus((string)$row['status']),(string)($row['matched_target_type']??''),(string)($row['matched_target_public_id']??''),$row['matched_at']===null?null:(int)$row['matched_at']);}
    private function assertTransaction():void{if(!$this->connection->inTransaction()){throw new \LogicException('Banktransactieopslag vereist een actieve transactie.');}}private function json(array$value):string{$json=json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($json===false){throw new \UnexpectedValueException('Banksnapshot kon niet worden gecodeerd.');}return$json;}private function decode(string$json):array{$value=json_decode($json,true);if(!is_array($value)||json_last_error()!==JSON_ERROR_NONE){throw new \UnexpectedValueException('Ongeldige banksnapshot.');}return$value;}
}
