<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminBanking\Infrastructure\Persistence;
use Flexgrid\Modules\AdminBanking\Contract\BankMatchProposalRepositoryInterface;use Flexgrid\Modules\AdminBanking\Domain\Model\BankMatchProposal;use Flexgrid\Modules\AdminCore\ValueObject\TenantId;
final class PdoBankMatchProposalRepository implements BankMatchProposalRepositoryInterface
{
    private$connection;public function __construct(\PDO$connection){$this->connection=$connection;}
    public function findByTransaction(TenantId$tenant,string$transactionPublicId):array{$statement=$this->connection->prepare('SELECT * FROM `admin_bank_match_proposal` WHERE `tenant_id`=:tenant AND `transaction_public_id`=:transaction ORDER BY `confidence_basis_points` DESC,`id`');$statement->execute([':tenant'=>$tenant->toString(),':transaction'=>trim($transactionPublicId)]);$items=[];foreach($statement->fetchAll(\PDO::FETCH_ASSOC)as$row){$items[]=new BankMatchProposal((string)$row['public_id'],new TenantId((string)$row['tenant_id']),(string)$row['transaction_public_id'],(string)$row['target_type'],(string)$row['target_public_id'],(int)$row['confidence_basis_points'],(string)$row['reason'],(int)$row['created_at']);}return$items;}
    public function replaceForTransaction(TenantId$tenant,string$transactionPublicId,array$proposals):void{$this->assertTransaction();foreach($proposals as$proposal){if(!$proposal instanceof BankMatchProposal||!$proposal->getTenantId()->equals($tenant)||$proposal->getTransactionPublicId()!==$transactionPublicId){throw new \InvalidArgumentException('Matchvoorstel hoort niet bij de actieve banktransactie.');}}$delete=$this->connection->prepare('DELETE FROM `admin_bank_match_proposal` WHERE `tenant_id`=:tenant AND `transaction_public_id`=:transaction');$delete->execute([':tenant'=>$tenant->toString(),':transaction'=>$transactionPublicId]);$insert=$this->connection->prepare('INSERT INTO `admin_bank_match_proposal` (`tenant_id`,`public_id`,`transaction_public_id`,`target_type`,`target_public_id`,`confidence_basis_points`,`reason`,`created_at`) VALUES (:tenant,:public,:transaction,:type,:target,:confidence,:reason,:created)');foreach($proposals as$proposal){$insert->execute([':tenant'=>$tenant->toString(),':public'=>$proposal->getPublicId(),':transaction'=>$transactionPublicId,':type'=>$proposal->getTargetType(),':target'=>$proposal->getTargetPublicId(),':confidence'=>$proposal->getConfidenceBasisPoints(),':reason'=>$proposal->getReason(),':created'=>$proposal->getCreatedAt()]);}}
    private function assertTransaction():void{if(!$this->connection->inTransaction()){throw new \LogicException('Matchvoorstelopslag vereist een actieve transactie.');}}
}
