<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminBanking\Domain\Model;
use Flexgrid\Modules\AdminCore\ValueObject\Money;use Flexgrid\Modules\AdminCore\ValueObject\TenantId;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\BankDate;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\BankSourceSnapshot;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\BankTransactionStatus;use Flexgrid\Modules\AdminBanking\Domain\ValueObject\CounterpartySnapshot;
final class BankTransaction
{
    private$publicId,$tenantId,$bankAccountPublicId,$bankImportPublicId,$externalId,$bookedOn,$amount,$counterparty,$description,$reference,$source,$status,$matchedTargetType,$matchedTargetPublicId,$matchedAt;
    public function __construct(string$publicId,TenantId$tenantId,string$account,string$import,string$externalId,BankDate$bookedOn,Money$amount,CounterpartySnapshot$counterparty,string$description,string$reference,BankSourceSnapshot$source,?BankTransactionStatus$status=null,string$targetType='',string$targetPublicId='',?int$matchedAt=null){$publicId=trim($publicId);$account=trim($account);$import=trim($import);$externalId=trim($externalId);$description=trim($description);$reference=trim($reference);$targetType=strtolower(trim($targetType));$targetPublicId=trim($targetPublicId);if($publicId===''||strlen($publicId)>64||$account===''||strlen($account)>64||$import===''||strlen($import)>64||$externalId===''||strlen($externalId)>128){throw new \InvalidArgumentException('Banktransactie vereist geldige publieke en externe ids.');}if($amount->isZero()||strlen($description)>2000||strlen($reference)>255){throw new \InvalidArgumentException('Banktransactie vereist een niet-nulbedrag en geldige tekstvelden.');}$status=$status?:new BankTransactionStatus(BankTransactionStatus::UNMATCHED);$hasTarget=$targetType!==''||$targetPublicId!==''||$matchedAt!==null;if($status->getValue()===BankTransactionStatus::MATCHED){if(preg_match('/^[a-z][a-z0-9_]{1,31}$/D',$targetType)!==1||$targetPublicId===''||strlen($targetPublicId)>64||$matchedAt===null||$matchedAt<0){throw new \InvalidArgumentException('Gematchte banktransactie vereist een geldig publiek doel.');}}elseif($hasTarget){throw new \InvalidArgumentException('Alleen een gematchte banktransactie mag een doel hebben.');}$this->publicId=$publicId;$this->tenantId=$tenantId;$this->bankAccountPublicId=$account;$this->bankImportPublicId=$import;$this->externalId=$externalId;$this->bookedOn=$bookedOn;$this->amount=$amount;$this->counterparty=$counterparty;$this->description=$description;$this->reference=$reference;$this->source=$source;$this->status=$status;$this->matchedTargetType=$targetType;$this->matchedTargetPublicId=$targetPublicId;$this->matchedAt=$matchedAt;}
    public function match(string$targetType,string$targetPublicId,int$matchedAt):void{$targetType=strtolower(trim($targetType));$targetPublicId=trim($targetPublicId);if($this->status->getValue()===BankTransactionStatus::MATCHED){if($this->matchedTargetType===$targetType&&$this->matchedTargetPublicId===$targetPublicId){return;}throw new \DomainException('Banktransactie is al aan een ander doel afgeletterd.');}if($this->status->getValue()!==BankTransactionStatus::UNMATCHED){throw new \DomainException('Alleen een open banktransactie kan worden afgeletterd.');}if(preg_match('/^[a-z][a-z0-9_]{1,31}$/D',$targetType)!==1||$targetPublicId===''||strlen($targetPublicId)>64||$matchedAt<0){throw new \InvalidArgumentException('Ongeldig afletterdoel.');}$this->status=new BankTransactionStatus(BankTransactionStatus::MATCHED);$this->matchedTargetType=$targetType;$this->matchedTargetPublicId=$targetPublicId;$this->matchedAt=$matchedAt;}
    public function ignore():void{if($this->status->getValue()===BankTransactionStatus::IGNORED){return;}if($this->status->getValue()!==BankTransactionStatus::UNMATCHED){throw new \DomainException('Alleen een open banktransactie kan worden genegeerd.');}$this->status=new BankTransactionStatus(BankTransactionStatus::IGNORED);}
    public function getPublicId():string{return$this->publicId;}public function getTenantId():TenantId{return$this->tenantId;}public function getBankAccountPublicId():string{return$this->bankAccountPublicId;}public function getBankImportPublicId():string{return$this->bankImportPublicId;}public function getExternalId():string{return$this->externalId;}public function getBookedOn():BankDate{return$this->bookedOn;}public function getAmount():Money{return$this->amount;}public function getCounterparty():CounterpartySnapshot{return$this->counterparty;}public function getDescription():string{return$this->description;}public function getReference():string{return$this->reference;}public function getSourceSnapshot():BankSourceSnapshot{return$this->source;}public function getStatus():BankTransactionStatus{return$this->status;}public function getMatchedTargetType():string{return$this->matchedTargetType;}public function getMatchedTargetPublicId():string{return$this->matchedTargetPublicId;}public function getMatchedAt():?int{return$this->matchedAt;}
}
